"""راهنمای ربات به زبان‌های غیرفارسی.

متن فارسی در `handlers/guide.py` می‌ماند چون به قیمت و سقف طرح‌ها وابسته
است و از روی همان مقادیر ساخته می‌شود. اینجا فقط ترجمه‌ها هستند: متنِ
ثابت، بدون محاسبه.

هر بخشی که هنوز ترجمه نشده باشد خودبه‌خود فارسی می‌ماند — نه خالی
می‌شود و نه ناقص. پس می‌شود زبان‌ها را کم‌کم کامل کرد بدون اینکه چیزی
بشکند.
"""
from __future__ import annotations

RULE = "━━━━━━━━━━━━━━━━━━"

# کلید بخش → {زبان: عنوان دکمه}
TITLES: dict[str, dict[str, str]] = {
    "start": {
        "en": "🚀 Quick start", "ar": "🚀 بداية سريعة", "ru": "🚀 Быстрый старт",
        "tr": "🚀 Hızlı başlangıç", "uz": "🚀 Tez boshlash",
        "hi": "🚀 त्वरित शुरुआत", "id": "🚀 Mulai cepat", "pt": "🚀 Início rápido",
    },
    "account": {
        "en": "👤 Connecting your account", "ar": "👤 ربط حسابك",
        "ru": "👤 Подключение аккаунта", "tr": "👤 Hesabı bağlama",
        "uz": "👤 Hisobni ulash", "hi": "👤 खाता जोड़ना",
        "id": "👤 Menghubungkan akun", "pt": "👤 Conectar sua conta",
    },
    "tasks": {
        "en": "📋 What is a copy job", "ar": "📋 ما هي مهمة النسخ",
        "ru": "📋 Что такое задача", "tr": "📋 Kopyalama işi nedir",
        "uz": "📋 Nusxalash vazifasi nima", "hi": "📋 कॉपी कार्य क्या है",
        "id": "📋 Apa itu tugas salin", "pt": "📋 O que é uma tarefa",
    },
    "dests": {
        "en": "📤 Several destinations", "ar": "📤 عدة وجهات",
        "ru": "📤 Несколько каналов", "tr": "📤 Birden çok hedef",
        "uz": "📤 Bir nechta manzil", "hi": "📤 कई गंतव्य",
        "id": "📤 Beberapa tujuan", "pt": "📤 Vários destinos",
    },
}

# کلید بخش → {زبان: متن کامل}
BODIES: dict[str, dict[str, str]] = {
    # ------------------------------------------------------------ خانه
    "home": {
        "en": (
            "📚 <b>Bot guide</b>\n"
            f"{RULE}\n\n"
            "This bot republishes any channel's posts in your own channel — "
            "automatically, instantly, and edited the way you want — "
            "<b>without you being an admin of the source channel</b>.\n\n"
            "New here? Start with «🚀 Quick start».\n\n"
            "Pick a topic 👇"
        ),
        "ar": (
            "📚 <b>دليل البوت</b>\n"
            f"{RULE}\n\n"
            "ينشر هذا البوت منشورات أي قناة في قناتك — تلقائياً وفوراً "
            "وبالتعديلات التي تريدها — <b>دون أن تكون مشرفاً في القناة "
            "المصدر</b>.\n\n"
            "جديد هنا؟ ابدأ من «🚀 بداية سريعة».\n\n"
            "اختر موضوعاً 👇"
        ),
        "ru": (
            "📚 <b>Руководство</b>\n"
            f"{RULE}\n\n"
            "Бот публикует посты любого канала у вас — автоматически, "
            "мгновенно и с нужными правками — <b>при этом вам не нужно быть "
            "админом исходного канала</b>.\n\n"
            "Впервые здесь? Начните с «🚀 Быстрый старт».\n\n"
            "Выберите тему 👇"
        ),
        "tr": (
            "📚 <b>Bot rehberi</b>\n"
            f"{RULE}\n\n"
            "Bu bot, herhangi bir kanalın gönderilerini kendi kanalınızda "
            "yayınlar — otomatik, anında ve istediğiniz gibi düzenlenmiş — "
            "<b>kaynak kanalda yönetici olmanıza gerek kalmadan</b>.\n\n"
            "Yeni misiniz? «🚀 Hızlı başlangıç» ile başlayın.\n\n"
            "Bir konu seçin 👇"
        ),
        "uz": (
            "📚 <b>Bot qoʻllanmasi</b>\n"
            f"{RULE}\n\n"
            "Bu bot istalgan kanalning postlarini oʻz kanalingizda chop etadi — "
            "avtomatik, bir zumda va siz xohlagandek tahrirlangan holda — "
            "<b>manba kanalda admin boʻlishingiz shart emas</b>.\n\n"
            "Yangimisiz? «🚀 Tez boshlash»dan boshlang.\n\n"
            "Mavzuni tanlang 👇"
        ),
        "hi": (
            "📚 <b>बॉट गाइड</b>\n"
            f"{RULE}\n\n"
            "यह बॉट किसी भी चैनल की पोस्ट आपके चैनल में दोबारा प्रकाशित करता है — "
            "अपने आप, तुरंत, और आपकी पसंद के अनुसार संपादित — <b>और इसके लिए "
            "आपको स्रोत चैनल का एडमिन होने की ज़रूरत नहीं</b>।\n\n"
            "नए हैं? «🚀 त्वरित शुरुआत» से शुरू करें।\n\n"
            "एक विषय चुनें 👇"
        ),
        "id": (
            "📚 <b>Panduan bot</b>\n"
            f"{RULE}\n\n"
            "Bot ini menerbitkan ulang postingan channel mana pun di channel "
            "Anda — otomatis, seketika, dan disunting sesuai keinginan Anda — "
            "<b>tanpa Anda harus menjadi admin channel sumber</b>.\n\n"
            "Baru di sini? Mulai dari «🚀 Mulai cepat».\n\n"
            "Pilih topik 👇"
        ),
        "pt": (
            "📚 <b>Guia do bot</b>\n"
            f"{RULE}\n\n"
            "Este bot republica as postagens de qualquer canal no seu — "
            "automaticamente, na hora e editadas do seu jeito — <b>sem que "
            "você precise ser admin do canal de origem</b>.\n\n"
            "Novo por aqui? Comece por «🚀 Início rápido».\n\n"
            "Escolha um tópico 👇"
        ),
    },
    # ----------------------------------------------------- شروع سریع
    "start": {
        "en": (
            "🚀 <b>Quick start — 3 steps</b>\n"
            f"{RULE}\n\n"
            "<b>Step 1 — Connect your account</b>\n"
            "«👤 Account» → «🔐 Connect account»\n"
            "Send your phone number with the country code (like "
            "<code>+447700900123</code>), then the code Telegram sends you.\n"
            "<i>Why is this needed? Telegram bots can only see posts in "
            "channels where they are admins. This bot reads the source channel "
            "using your account, so you never have to be an admin anywhere.</i>\n\n"
            "<b>Step 2 — Create a copy job</b>\n"
            "«➕ New job» → source channel → destination channel\n"
            "You can type the @username or pick from your chat list.\n"
            "⚠️ Your account must be allowed to post in the <b>destination</b>.\n\n"
            "<b>Step 3 — Set it up</b>\n"
            "Open the job and set filters, word replacements, your sign-off "
            "and watermark.\n\n"
            "✅ That's it. The job is live from the moment you create it, and "
            "the source channel's next post gets copied.\n\n"
            "<i>Tip: before anything is actually sent, use «🧪 Test settings» "
            "to see the result.</i>"
        ),
        "ar": (
            "🚀 <b>بداية سريعة — ٣ خطوات</b>\n"
            f"{RULE}\n\n"
            "<b>الخطوة ١ — اربط حسابك</b>\n"
            "«👤 الحساب» ← «🔐 ربط الحساب»\n"
            "أرسل رقم هاتفك مع رمز الدولة، ثم الرمز الذي يرسله تلجرام.\n"
            "<i>لماذا؟ لأن بوتات تلجرام لا ترى إلا منشورات القنوات التي هي "
            "مشرفة فيها. هذا البوت يقرأ القناة المصدر بحسابك أنت، فلا تحتاج "
            "لأن تكون مشرفاً في أي مكان.</i>\n\n"
            "<b>الخطوة ٢ — أنشئ مهمة نسخ</b>\n"
            "«➕ مهمة جديدة» ← القناة المصدر ← القناة الهدف\n"
            "يمكنك كتابة المعرّف أو الاختيار من قائمة محادثاتك.\n"
            "⚠️ يجب أن يكون لحسابك صلاحية النشر في القناة <b>الهدف</b>.\n\n"
            "<b>الخطوة ٣ — اضبطها</b>\n"
            "افتح المهمة واضبط الفلاتر واستبدال الكلمات وتوقيعك والعلامة "
            "المائية.\n\n"
            "✅ هذا كل شيء. المهمة تعمل من لحظة إنشائها، وأول منشور جديد في "
            "القناة المصدر سيُنسخ.\n\n"
            "<i>نصيحة: قبل أن يُرسل أي شيء فعلياً، استخدم «🧪 اختبار "
            "الإعدادات» لترى النتيجة.</i>"
        ),
        "ru": (
            "🚀 <b>Быстрый старт — 3 шага</b>\n"
            f"{RULE}\n\n"
            "<b>Шаг 1 — Подключите аккаунт</b>\n"
            "«👤 Аккаунт» → «🔐 Подключить аккаунт»\n"
            "Отправьте номер телефона с кодом страны, затем код из Telegram.\n"
            "<i>Зачем это? Боты Telegram видят посты только в тех каналах, где "
            "они админы. Этот бот читает исходный канал вашим аккаунтом, "
            "поэтому вам нигде не нужно быть админом.</i>\n\n"
            "<b>Шаг 2 — Создайте задачу</b>\n"
            "«➕ Новая задача» → исходный канал → целевой канал\n"
            "Можно ввести @username или выбрать из списка чатов.\n"
            "⚠️ Ваш аккаунт должен иметь право публиковать в <b>целевом</b> канале.\n\n"
            "<b>Шаг 3 — Настройте</b>\n"
            "Откройте задачу и задайте фильтры, замены слов, подпись и водяной знак.\n\n"
            "✅ Готово. Задача работает с момента создания, и следующий пост "
            "исходного канала будет скопирован.\n\n"
            "<i>Совет: прежде чем что-то реально отправится, нажмите "
            "«🧪 Проверить настройки» и посмотрите результат.</i>"
        ),
        "tr": (
            "🚀 <b>Hızlı başlangıç — 3 adım</b>\n"
            f"{RULE}\n\n"
            "<b>Adım 1 — Hesabınızı bağlayın</b>\n"
            "«👤 Hesap» → «🔐 Hesabı bağla»\n"
            "Telefon numaranızı ülke koduyla gönderin, sonra Telegram'ın "
            "gönderdiği kodu girin.\n"
            "<i>Neden gerekli? Telegram botları yalnızca yönetici oldukları "
            "kanalların gönderilerini görebilir. Bu bot kaynak kanalı sizin "
            "hesabınızla okur, böylece hiçbir yerde yönetici olmanız "
            "gerekmez.</i>\n\n"
            "<b>Adım 2 — Bir kopyalama işi oluşturun</b>\n"
            "«➕ Yeni iş» → kaynak kanal → hedef kanal\n"
            "@kullanıcı adını yazabilir veya sohbet listenizden seçebilirsiniz.\n"
            "⚠️ Hesabınızın <b>hedef</b> kanalda gönderi yetkisi olmalı.\n\n"
            "<b>Adım 3 — Ayarlayın</b>\n"
            "İşi açın; filtreleri, kelime değişimlerini, imzanızı ve "
            "filigranı ayarlayın.\n\n"
            "✅ Bu kadar. İş oluşturduğunuz andan itibaren çalışır ve kaynak "
            "kanalın bir sonraki gönderisi kopyalanır.\n\n"
            "<i>İpucu: gerçekten bir şey gönderilmeden önce «🧪 Ayarları "
            "test et» ile sonucu görün.</i>"
        ),
        "uz": (
            "🚀 <b>Tez boshlash — 3 qadam</b>\n"
            f"{RULE}\n\n"
            "<b>1-qadam — Hisobingizni ulang</b>\n"
            "«👤 Hisob» → «🔐 Hisobni ulash»\n"
            "Telefon raqamingizni mamlakat kodi bilan yuboring, keyin "
            "Telegram yuborgan kodni kiriting.\n"
            "<i>Nega kerak? Telegram botlari faqat oʻzlari admin boʻlgan "
            "kanallarning postlarini koʻra oladi. Bu bot manba kanalni sizning "
            "hisobingiz bilan oʻqiydi, shuning uchun hech qayerda admin "
            "boʻlishingiz shart emas.</i>\n\n"
            "<b>2-qadam — Nusxalash vazifasini yarating</b>\n"
            "«➕ Yangi vazifa» → manba kanal → maqsad kanal\n"
            "@foydalanuvchi nomini yozishingiz yoki chatlar roʻyxatidan "
            "tanlashingiz mumkin.\n"
            "⚠️ Hisobingizda <b>maqsad</b> kanalda post joylash huquqi "
            "boʻlishi kerak.\n\n"
            "<b>3-qadam — Sozlang</b>\n"
            "Vazifani oching va filtrlar, soʻz almashtirishlari, imzoyingiz "
            "va suv belgisini sozlang.\n\n"
            "✅ Tamom. Vazifa yaratilgan paytdan ishlaydi va manba kanalning "
            "keyingi posti nusxalanadi.\n\n"
            "<i>Maslahat: haqiqatan biror narsa yuborilishidan oldin "
            "«🧪 Sozlamalarni sinash» bilan natijani koʻring.</i>"
        ),
        "hi": (
            "🚀 <b>त्वरित शुरुआत — 3 चरण</b>\n"
            f"{RULE}\n\n"
            "<b>चरण 1 — अपना खाता जोड़ें</b>\n"
            "«👤 खाता» → «🔐 खाता जोड़ें»\n"
            "देश कोड सहित अपना फ़ोन नंबर भेजें, फिर टेलीग्राम द्वारा भेजा गया "
            "कोड डालें।\n"
            "<i>यह क्यों ज़रूरी है? टेलीग्राम बॉट केवल उन्हीं चैनलों की पोस्ट "
            "देख सकते हैं जहाँ वे एडमिन हों। यह बॉट स्रोत चैनल आपके खाते से "
            "पढ़ता है, इसलिए आपको कहीं भी एडमिन बनने की ज़रूरत नहीं।</i>\n\n"
            "<b>चरण 2 — एक कॉपी कार्य बनाएँ</b>\n"
            "«➕ नया कार्य» → स्रोत चैनल → गंतव्य चैनल\n"
            "आप @यूज़रनेम टाइप कर सकते हैं या अपनी चैट सूची से चुन सकते हैं।\n"
            "⚠️ आपके खाते को <b>गंतव्य</b> चैनल में पोस्ट करने की अनुमति "
            "होनी चाहिए।\n\n"
            "<b>चरण 3 — इसे सेट करें</b>\n"
            "कार्य खोलें और फ़िल्टर, शब्द बदलाव, अपने हस्ताक्षर और वॉटरमार्क "
            "सेट करें।\n\n"
            "✅ बस इतना ही। कार्य बनते ही चालू हो जाता है और स्रोत चैनल की "
            "अगली पोस्ट कॉपी हो जाती है।\n\n"
            "<i>सुझाव: कुछ भी वास्तव में भेजे जाने से पहले «🧪 सेटिंग्स "
            "जाँचें» से परिणाम देखें।</i>"
        ),
        "id": (
            "🚀 <b>Mulai cepat — 3 langkah</b>\n"
            f"{RULE}\n\n"
            "<b>Langkah 1 — Hubungkan akun Anda</b>\n"
            "«👤 Akun» → «🔐 Hubungkan akun»\n"
            "Kirim nomor telepon Anda dengan kode negara, lalu kode yang "
            "dikirim Telegram.\n"
            "<i>Mengapa perlu? Bot Telegram hanya bisa melihat postingan di "
            "channel tempat mereka menjadi admin. Bot ini membaca channel "
            "sumber memakai akun Anda, jadi Anda tidak perlu jadi admin di "
            "mana pun.</i>\n\n"
            "<b>Langkah 2 — Buat tugas salin</b>\n"
            "«➕ Tugas baru» → channel sumber → channel tujuan\n"
            "Anda bisa mengetik @username atau memilih dari daftar chat.\n"
            "⚠️ Akun Anda harus punya izin memposting di channel <b>tujuan</b>.\n\n"
            "<b>Langkah 3 — Atur</b>\n"
            "Buka tugas dan atur filter, penggantian kata, tanda tangan dan "
            "watermark.\n\n"
            "✅ Selesai. Tugas aktif sejak dibuat, dan postingan berikutnya "
            "dari channel sumber akan disalin.\n\n"
            "<i>Tips: sebelum ada yang benar-benar terkirim, gunakan «🧪 Uji "
            "pengaturan» untuk melihat hasilnya.</i>"
        ),
        "pt": (
            "🚀 <b>Início rápido — 3 passos</b>\n"
            f"{RULE}\n\n"
            "<b>Passo 1 — Conecte sua conta</b>\n"
            "«👤 Conta» → «🔐 Conectar conta»\n"
            "Envie seu número de telefone com o código do país e depois o "
            "código que o Telegram enviar.\n"
            "<i>Por que isso é preciso? Bots do Telegram só enxergam posts de "
            "canais onde são admins. Este bot lê o canal de origem usando a "
            "sua conta, então você não precisa ser admin em lugar nenhum.</i>\n\n"
            "<b>Passo 2 — Crie uma tarefa de cópia</b>\n"
            "«➕ Nova tarefa» → canal de origem → canal de destino\n"
            "Você pode digitar o @usuário ou escolher da sua lista de conversas.\n"
            "⚠️ Sua conta precisa poder publicar no canal de <b>destino</b>.\n\n"
            "<b>Passo 3 — Configure</b>\n"
            "Abra a tarefa e defina filtros, substituições de palavras, sua "
            "assinatura e marca d'água.\n\n"
            "✅ Pronto. A tarefa fica ativa assim que é criada e o próximo "
            "post do canal de origem será copiado.\n\n"
            "<i>Dica: antes que algo seja realmente enviado, use «🧪 Testar "
            "configurações» para ver o resultado.</i>"
        ),
    },
    # -------------------------------------------------- اتصال اکانت
    "account": {
        "en": (
            "👤 <b>Connecting your account</b>\n"
            f"{RULE}\n\n"
            "The bot asks you once to sign in with your phone number.\n\n"
            "<b>What happens?</b>\n"
            "The bot creates a session from your account and uses it to:\n"
            "• read the source channel's posts\n"
            "• send the processed post to your destination channel\n\n"
            "<b>Security</b>\n"
            "• your session is stored <b>encrypted</b>\n"
            "• your password is never stored\n"
            "• sign out any time from the same screen\n"
            "• you can set a <b>security PIN</b> that is asked before sensitive "
            "actions (signing out, deleting a job)\n\n"
            "<b>If you have two-step verification</b>\n"
            "After the code you'll be asked for your two-step password. Send it."
        ),
        "ar": (
            "👤 <b>ربط حسابك</b>\n"
            f"{RULE}\n\n"
            "يطلب منك البوت مرة واحدة تسجيل الدخول برقم هاتفك.\n\n"
            "<b>ماذا يحدث؟</b>\n"
            "ينشئ البوت جلسة من حسابك ويستخدمها لـ:\n"
            "• قراءة منشورات القناة المصدر\n"
            "• إرسال المنشور بعد المعالجة إلى قناتك الهدف\n\n"
            "<b>الأمان</b>\n"
            "• جلستك تُحفظ <b>مشفّرة</b>\n"
            "• كلمة مرورك لا تُحفظ أبداً\n"
            "• يمكنك تسجيل الخروج في أي وقت من الشاشة نفسها\n"
            "• يمكنك ضبط <b>رمز أمان</b> يُطلب قبل العمليات الحساسة "
            "(تسجيل الخروج، حذف مهمة)\n\n"
            "<b>إذا كان لديك التحقق بخطوتين</b>\n"
            "بعد الرمز ستُسأل عن كلمة مرور الخطوتين. أرسلها."
        ),
        "ru": (
            "👤 <b>Подключение аккаунта</b>\n"
            f"{RULE}\n\n"
            "Бот один раз попросит войти по номеру телефона.\n\n"
            "<b>Что происходит?</b>\n"
            "Бот создаёт сессию вашего аккаунта и с её помощью:\n"
            "• читает посты исходного канала\n"
            "• отправляет обработанный пост в ваш канал\n\n"
            "<b>Безопасность</b>\n"
            "• сессия хранится <b>в зашифрованном виде</b>\n"
            "• пароль не сохраняется никогда\n"
            "• выйти можно в любой момент с того же экрана\n"
            "• можно задать <b>PIN-код</b>, который спрашивается перед "
            "важными действиями (выход, удаление задачи)\n\n"
            "<b>Если включена двухэтапная проверка</b>\n"
            "После кода спросят пароль двухэтапной проверки. Отправьте его."
        ),
        "tr": (
            "👤 <b>Hesabınızı bağlama</b>\n"
            f"{RULE}\n\n"
            "Bot bir kez telefon numaranızla giriş yapmanızı ister.\n\n"
            "<b>Ne oluyor?</b>\n"
            "Bot hesabınızdan bir oturum oluşturur ve bununla:\n"
            "• kaynak kanalın gönderilerini okur\n"
            "• işlenmiş gönderiyi hedef kanalınıza gönderir\n\n"
            "<b>Güvenlik</b>\n"
            "• oturumunuz <b>şifrelenmiş</b> olarak saklanır\n"
            "• parolanız asla saklanmaz\n"
            "• istediğiniz an aynı ekrandan çıkış yapabilirsiniz\n"
            "• hassas işlemlerden önce (çıkış, iş silme) sorulacak bir "
            "<b>güvenlik PIN'i</b> belirleyebilirsiniz\n\n"
            "<b>İki adımlı doğrulamanız varsa</b>\n"
            "Koddan sonra iki adımlı parolanız sorulur. Onu gönderin."
        ),
        "uz": (
            "👤 <b>Hisobingizni ulash</b>\n"
            f"{RULE}\n\n"
            "Bot bir marta telefon raqamingiz bilan kirishni soʻraydi.\n\n"
            "<b>Nima sodir boʻladi?</b>\n"
            "Bot hisobingizdan sessiya yaratadi va u bilan:\n"
            "• manba kanalning postlarini oʻqiydi\n"
            "• qayta ishlangan postni maqsad kanalingizga yuboradi\n\n"
            "<b>Xavfsizlik</b>\n"
            "• sessiyangiz <b>shifrlangan</b> holda saqlanadi\n"
            "• parolingiz hech qachon saqlanmaydi\n"
            "• istalgan vaqtda oʻsha ekrandan chiqishingiz mumkin\n"
            "• muhim amallardan oldin (chiqish, vazifani oʻchirish) "
            "soʻraladigan <b>xavfsizlik PIN</b>ini qoʻyishingiz mumkin\n\n"
            "<b>Ikki bosqichli tasdiqlash boʻlsa</b>\n"
            "Koddan keyin ikki bosqichli parol soʻraladi. Uni yuboring."
        ),
        "hi": (
            "👤 <b>अपना खाता जोड़ना</b>\n"
            f"{RULE}\n\n"
            "बॉट एक बार आपसे फ़ोन नंबर से साइन इन करने को कहता है।\n\n"
            "<b>क्या होता है?</b>\n"
            "बॉट आपके खाते से एक सेशन बनाता है और उससे:\n"
            "• स्रोत चैनल की पोस्ट पढ़ता है\n"
            "• संसाधित पोस्ट आपके गंतव्य चैनल में भेजता है\n\n"
            "<b>सुरक्षा</b>\n"
            "• आपका सेशन <b>एन्क्रिप्टेड</b> रखा जाता है\n"
            "• आपका पासवर्ड कभी संग्रहित नहीं होता\n"
            "• उसी स्क्रीन से कभी भी साइन आउट कर सकते हैं\n"
            "• आप एक <b>सुरक्षा पिन</b> रख सकते हैं जो संवेदनशील कामों "
            "(साइन आउट, कार्य हटाना) से पहले पूछा जाए\n\n"
            "<b>अगर टू-स्टेप वेरिफ़िकेशन है</b>\n"
            "कोड के बाद टू-स्टेप पासवर्ड पूछा जाएगा। उसे भेजें।"
        ),
        "id": (
            "👤 <b>Menghubungkan akun Anda</b>\n"
            f"{RULE}\n\n"
            "Bot meminta Anda sekali untuk masuk dengan nomor telepon.\n\n"
            "<b>Apa yang terjadi?</b>\n"
            "Bot membuat sesi dari akun Anda dan menggunakannya untuk:\n"
            "• membaca postingan channel sumber\n"
            "• mengirim postingan yang sudah diproses ke channel tujuan Anda\n\n"
            "<b>Keamanan</b>\n"
            "• sesi Anda disimpan <b>terenkripsi</b>\n"
            "• kata sandi Anda tidak pernah disimpan\n"
            "• keluar kapan saja dari layar yang sama\n"
            "• Anda bisa memasang <b>PIN keamanan</b> yang ditanyakan sebelum "
            "tindakan sensitif (keluar, menghapus tugas)\n\n"
            "<b>Jika Anda punya verifikasi dua langkah</b>\n"
            "Setelah kode, Anda akan ditanya kata sandi dua langkah. Kirimkan."
        ),
        "pt": (
            "👤 <b>Conectar sua conta</b>\n"
            f"{RULE}\n\n"
            "O bot pede uma vez que você entre com seu número de telefone.\n\n"
            "<b>O que acontece?</b>\n"
            "O bot cria uma sessão da sua conta e a usa para:\n"
            "• ler as postagens do canal de origem\n"
            "• enviar a postagem processada ao seu canal de destino\n\n"
            "<b>Segurança</b>\n"
            "• sua sessão é guardada <b>criptografada</b>\n"
            "• sua senha nunca é armazenada\n"
            "• saia quando quiser pela mesma tela\n"
            "• você pode definir um <b>PIN de segurança</b> pedido antes de "
            "ações sensíveis (sair, excluir uma tarefa)\n\n"
            "<b>Se você usa verificação em duas etapas</b>\n"
            "Depois do código será pedida a senha de duas etapas. Envie-a."
        ),
    },
    # ------------------------------------------------- کار کپی چیست
    "tasks": {
        "en": (
            "📋 <b>What is a copy job?</b>\n"
            f"{RULE}\n\n"
            "<b>1 job = 1 source channel → several destination channels</b>\n\n"
            "A few examples:\n"
            "• 1 channel to 1 channel → <b>1 job</b>\n"
            "• 3 different channels into yours → <b>3 jobs</b>\n"
            "• 1 channel into 5 of yours → <b>1 job with 5 destinations</b>\n"
            "• 3 channels into 5 → <b>3 jobs, 5 destinations each</b>\n\n"
            "<b>Why several destinations beat several jobs</b>\n"
            "Because the source channel is read and processed <b>once</b>. "
            "Five separate jobs would use five times the traffic and raise "
            "your chance of being rate-limited by Telegram.\n\n"
            "<b>Each job is configured on its own</b>\n"
            "Filters, word replacements, sign-off and schedule are independent "
            "per job. If you like one job's setup, copy it onto another with "
            "«📋 Copy settings».\n\n"
            "<b>Turning jobs on and off</b>\n"
            "🟢 means running, 🔴 means stopped. «⏸ Pause this job» turns it "
            "off temporarily without losing its settings."
        ),
        "ar": (
            "📋 <b>ما هي مهمة النسخ؟</b>\n"
            f"{RULE}\n\n"
            "<b>مهمة واحدة = قناة مصدر واحدة ← عدة قنوات هدف</b>\n\n"
            "أمثلة:\n"
            "• من قناة إلى قناة → <b>مهمة واحدة</b>\n"
            "• من ٣ قنوات مختلفة إلى قناتك → <b>٣ مهام</b>\n"
            "• من قناة إلى ٥ من قنواتك → <b>مهمة واحدة بـ ٥ وجهات</b>\n"
            "• من ٣ قنوات إلى ٥ → <b>٣ مهام، لكل منها ٥ وجهات</b>\n\n"
            "<b>لماذا الوجهات المتعددة أفضل من المهام المتعددة</b>\n"
            "لأن القناة المصدر تُقرأ وتُعالَج <b>مرة واحدة</b>. خمس مهام "
            "منفصلة تستهلك خمسة أضعاف حركة البيانات وترفع احتمال تقييدك من "
            "تلجرام.\n\n"
            "<b>كل مهمة تُضبط على حدة</b>\n"
            "الفلاتر واستبدال الكلمات والتوقيع والجدولة مستقلة لكل مهمة. إن "
            "أعجبك إعداد مهمة، انسخه إلى أخرى بـ «📋 نسخ الإعدادات».\n\n"
            "<b>التشغيل والإيقاف</b>\n"
            "🟢 تعمل، 🔴 متوقفة. «⏸ إيقاف هذه المهمة» يوقفها مؤقتاً دون "
            "فقدان إعداداتها."
        ),
        "ru": (
            "📋 <b>Что такое задача копирования?</b>\n"
            f"{RULE}\n\n"
            "<b>1 задача = 1 исходный канал → несколько целевых каналов</b>\n\n"
            "Примеры:\n"
            "• из 1 канала в 1 → <b>1 задача</b>\n"
            "• из 3 разных каналов в ваш → <b>3 задачи</b>\n"
            "• из 1 канала в 5 ваших → <b>1 задача с 5 каналами</b>\n"
            "• из 3 каналов в 5 → <b>3 задачи, по 5 каналов в каждой</b>\n\n"
            "<b>Почему несколько каналов лучше нескольких задач</b>\n"
            "Потому что исходный канал читается и обрабатывается <b>один "
            "раз</b>. Пять отдельных задач дали бы впятеро больше трафика и "
            "повысили риск ограничений со стороны Telegram.\n\n"
            "<b>Каждая задача настраивается отдельно</b>\n"
            "Фильтры, замены слов, подпись и расписание независимы. Понравилась "
            "настройка одной задачи — перенесите её кнопкой "
            "«📋 Копировать настройки».\n\n"
            "<b>Включение и выключение</b>\n"
            "🟢 — работает, 🔴 — остановлена. «⏸ Приостановить» выключает "
            "задачу временно, настройки сохраняются."
        ),
        "tr": (
            "📋 <b>Kopyalama işi nedir?</b>\n"
            f"{RULE}\n\n"
            "<b>1 iş = 1 kaynak kanal → birden çok hedef kanal</b>\n\n"
            "Birkaç örnek:\n"
            "• 1 kanaldan 1 kanala → <b>1 iş</b>\n"
            "• 3 farklı kanaldan sizinkine → <b>3 iş</b>\n"
            "• 1 kanaldan sizin 5 kanalınıza → <b>5 hedefli 1 iş</b>\n"
            "• 3 kanaldan 5 kanala → <b>3 iş, her biri 5 hedefli</b>\n\n"
            "<b>Neden çok hedef, çok işten iyidir</b>\n"
            "Çünkü kaynak kanal <b>bir kez</b> okunup işlenir. Beş ayrı iş beş "
            "kat trafik harcar ve Telegram tarafından kısıtlanma ihtimalinizi "
            "artırır.\n\n"
            "<b>Her iş ayrı ayarlanır</b>\n"
            "Filtreler, kelime değişimleri, imza ve zamanlama her iş için "
            "bağımsızdır. Bir işin ayarını beğendiyseniz «📋 Ayarları kopyala» "
            "ile diğerine aktarın.\n\n"
            "<b>Açma ve kapama</b>\n"
            "🟢 çalışıyor, 🔴 durmuş demektir. «⏸ Bu işi durdur» ayarları "
            "kaybetmeden geçici olarak kapatır."
        ),
        "uz": (
            "📋 <b>Nusxalash vazifasi nima?</b>\n"
            f"{RULE}\n\n"
            "<b>1 vazifa = 1 manba kanal → bir nechta maqsad kanal</b>\n\n"
            "Bir nechta misol:\n"
            "• 1 kanaldan 1 kanalga → <b>1 vazifa</b>\n"
            "• 3 xil kanaldan sizinkiga → <b>3 vazifa</b>\n"
            "• 1 kanaldan sizning 5 kanalingizga → <b>5 manzilli 1 vazifa</b>\n"
            "• 3 kanaldan 5 kanalga → <b>3 vazifa, har birida 5 manzil</b>\n\n"
            "<b>Nega koʻp manzil koʻp vazifadan yaxshi</b>\n"
            "Chunki manba kanal <b>bir marta</b> oʻqiladi va qayta ishlanadi. "
            "Beshta alohida vazifa besh barobar trafik sarflaydi va Telegram "
            "tomonidan cheklanish ehtimolini oshiradi.\n\n"
            "<b>Har bir vazifa alohida sozlanadi</b>\n"
            "Filtrlar, soʻz almashtirishlari, imzo va jadval har bir vazifa "
            "uchun mustaqil. Bir vazifaning sozlamasi yoqsa, «📋 Sozlamalarni "
            "nusxalash» bilan boshqasiga koʻchiring.\n\n"
            "<b>Yoqish va oʻchirish</b>\n"
            "🟢 ishlayapti, 🔴 toʻxtagan. «⏸ Bu vazifani toʻxtatish» "
            "sozlamalarni yoʻqotmasdan vaqtincha oʻchiradi."
        ),
        "hi": (
            "📋 <b>कॉपी कार्य क्या है?</b>\n"
            f"{RULE}\n\n"
            "<b>1 कार्य = 1 स्रोत चैनल → कई गंतव्य चैनल</b>\n\n"
            "कुछ उदाहरण:\n"
            "• 1 चैनल से 1 चैनल → <b>1 कार्य</b>\n"
            "• 3 अलग चैनलों से आपके चैनल में → <b>3 कार्य</b>\n"
            "• 1 चैनल से आपके 5 चैनलों में → <b>5 गंतव्यों वाला 1 कार्य</b>\n"
            "• 3 चैनलों से 5 में → <b>3 कार्य, हर एक में 5 गंतव्य</b>\n\n"
            "<b>कई गंतव्य कई कार्यों से बेहतर क्यों</b>\n"
            "क्योंकि स्रोत चैनल <b>एक ही बार</b> पढ़ा और संसाधित होता है। पाँच "
            "अलग कार्य पाँच गुना ट्रैफ़िक खर्च करेंगे और टेलीग्राम द्वारा "
            "सीमित किए जाने की संभावना बढ़ाएँगे।\n\n"
            "<b>हर कार्य अलग से सेट होता है</b>\n"
            "फ़िल्टर, शब्द बदलाव, हस्ताक्षर और शेड्यूल हर कार्य के लिए स्वतंत्र "
            "हैं। किसी कार्य की सेटिंग पसंद आए तो «📋 सेटिंग्स कॉपी करें» से "
            "दूसरे पर ले जाएँ।\n\n"
            "<b>चालू और बंद करना</b>\n"
            "🟢 यानी चल रहा है, 🔴 यानी रुका हुआ। «⏸ यह कार्य रोकें» सेटिंग्स "
            "खोए बिना अस्थायी रूप से बंद कर देता है।"
        ),
        "id": (
            "📋 <b>Apa itu tugas salin?</b>\n"
            f"{RULE}\n\n"
            "<b>1 tugas = 1 channel sumber → beberapa channel tujuan</b>\n\n"
            "Beberapa contoh:\n"
            "• 1 channel ke 1 channel → <b>1 tugas</b>\n"
            "• 3 channel berbeda ke channel Anda → <b>3 tugas</b>\n"
            "• 1 channel ke 5 channel Anda → <b>1 tugas dengan 5 tujuan</b>\n"
            "• 3 channel ke 5 → <b>3 tugas, masing-masing 5 tujuan</b>\n\n"
            "<b>Mengapa banyak tujuan lebih baik daripada banyak tugas</b>\n"
            "Karena channel sumber dibaca dan diproses <b>sekali saja</b>. Lima "
            "tugas terpisah memakai lima kali lipat trafik dan menaikkan "
            "peluang Anda dibatasi Telegram.\n\n"
            "<b>Tiap tugas diatur sendiri</b>\n"
            "Filter, penggantian kata, tanda tangan dan jadwal berdiri sendiri "
            "per tugas. Kalau suka pengaturan satu tugas, salin ke tugas lain "
            "dengan «📋 Salin pengaturan».\n\n"
            "<b>Menyalakan dan mematikan</b>\n"
            "🟢 berarti berjalan, 🔴 berarti berhenti. «⏸ Jeda tugas ini» "
            "mematikannya sementara tanpa kehilangan pengaturan."
        ),
        "pt": (
            "📋 <b>O que é uma tarefa de cópia?</b>\n"
            f"{RULE}\n\n"
            "<b>1 tarefa = 1 canal de origem → vários canais de destino</b>\n\n"
            "Alguns exemplos:\n"
            "• de 1 canal para 1 canal → <b>1 tarefa</b>\n"
            "• de 3 canais diferentes para o seu → <b>3 tarefas</b>\n"
            "• de 1 canal para 5 seus → <b>1 tarefa com 5 destinos</b>\n"
            "• de 3 canais para 5 → <b>3 tarefas, 5 destinos cada</b>\n\n"
            "<b>Por que vários destinos são melhores que várias tarefas</b>\n"
            "Porque o canal de origem é lido e processado <b>uma única vez</b>. "
            "Cinco tarefas separadas gastariam cinco vezes mais tráfego e "
            "aumentariam a chance de você ser limitado pelo Telegram.\n\n"
            "<b>Cada tarefa é configurada sozinha</b>\n"
            "Filtros, substituições de palavras, assinatura e agendamento são "
            "independentes por tarefa. Gostou da configuração de uma? Copie "
            "para outra com «📋 Copiar configurações».\n\n"
            "<b>Ligar e desligar</b>\n"
            "🟢 significa rodando, 🔴 parada. «⏸ Pausar esta tarefa» desliga "
            "temporariamente sem perder as configurações."
        ),
    },
    # ---------------------------------------------------- چند مقصد
    "dests": {
        "en": (
            "📤 <b>Several destinations, each with its own sign-off</b>\n"
            f"{RULE}\n\n"
            "In a job's menu → «📤 Destination channels»\n\n"
            "The first destination is the ⭐️ main one. Add more with "
            "«➕ Add destination»; every post goes to all of them.\n\n"
            "<b>✍️ Per-channel sign-off</b>\n"
            "Next to each destination there is a button:\n"
            "• ➕ means it has no own sign-off (it uses the job's settings)\n"
            "• ✍️ means it has its own\n\n"
            "Tapping it lets you set, for <b>that channel alone</b>:\n"
            "🔻 footer  |  🔝 header  |  🖋 replacement signature\n\n"
            "So you can put one piece of news into three of your channels at "
            "once, each signed with its own handle.\n\n"
            "Everything else (filters, word replacements, watermark) comes from "
            "the job itself — you set it once and only change the sign-off.\n\n"
            "🟢/🔴 next to a destination turns it on or off temporarily, "
            "🗑 removes it."
        ),
        "ar": (
            "📤 <b>عدة وجهات، لكل منها توقيعها</b>\n"
            f"{RULE}\n\n"
            "في قائمة المهمة ← «📤 قنوات الوجهة»\n\n"
            "الوجهة الأولى هي ⭐️ الرئيسية. أضف غيرها بـ «➕ إضافة وجهة»؛ كل "
            "منشور يذهب إليها جميعاً.\n\n"
            "<b>✍️ توقيع خاص لكل قناة</b>\n"
            "بجانب كل وجهة زر:\n"
            "• ➕ يعني لا توقيع خاص لها (تستخدم إعدادات المهمة)\n"
            "• ✍️ يعني لها توقيعها\n\n"
            "بالضغط عليه تضبط لـ<b>تلك القناة وحدها</b>:\n"
            "🔻 التذييل  |  🔝 الترويسة  |  🖋 التوقيع البديل\n\n"
            "هكذا تضع خبراً واحداً في ثلاث من قنواتك دفعة واحدة، ويوقَّع كل "
            "منها بمعرّفها.\n\n"
            "كل ما عدا ذلك (الفلاتر، استبدال الكلمات، العلامة المائية) يأتي من "
            "المهمة نفسها — تضبطه مرة وتغيّر التوقيع فقط.\n\n"
            "🟢/🔴 بجانب الوجهة يشغّلها أو يوقفها مؤقتاً، و🗑 يحذفها."
        ),
        "ru": (
            "📤 <b>Несколько каналов, у каждого своя подпись</b>\n"
            f"{RULE}\n\n"
            "В меню задачи → «📤 Целевые каналы»\n\n"
            "Первый канал — ⭐️ основной. Добавляйте остальные кнопкой "
            "«➕ Добавить канал»; каждый пост уходит во все.\n\n"
            "<b>✍️ Своя подпись для каждого канала</b>\n"
            "Рядом с каждым каналом есть кнопка:\n"
            "• ➕ — своей подписи нет (берутся настройки задачи)\n"
            "• ✍️ — своя подпись задана\n\n"
            "Нажав её, вы задаёте <b>только для этого канала</b>:\n"
            "🔻 футер  |  🔝 хедер  |  🖋 подпись-замену\n\n"
            "Так одну новость можно разом положить в три своих канала, и под "
            "каждой будет её собственный ник.\n\n"
            "Всё остальное (фильтры, замены слов, водяной знак) берётся из "
            "самой задачи — настраиваете один раз и меняете только подпись.\n\n"
            "🟢/🔴 рядом с каналом временно включает или выключает его, "
            "🗑 удаляет."
        ),
        "tr": (
            "📤 <b>Birden çok hedef, her birine özel imza</b>\n"
            f"{RULE}\n\n"
            "İş menüsünde → «📤 Hedef kanallar»\n\n"
            "İlk hedef ⭐️ ana hedeftir. «➕ Hedef ekle» ile diğerlerini "
            "ekleyin; her gönderi hepsine gider.\n\n"
            "<b>✍️ Kanala özel imza</b>\n"
            "Her hedefin yanında bir düğme var:\n"
            "• ➕ kendi imzası yok demek (işin ayarlarını kullanır)\n"
            "• ✍️ kendi imzası var demek\n\n"
            "Ona dokununca <b>yalnızca o kanal için</b> şunları ayarlarsınız:\n"
            "🔻 alt bilgi  |  🔝 üst bilgi  |  🖋 imza değişimi\n\n"
            "Böylece bir haberi aynı anda üç kanalınıza koyar, her birinin "
            "altına kendi adresini yazarsınız.\n\n"
            "Geri kalan her şey (filtreler, kelime değişimleri, filigran) işin "
            "kendisinden gelir — bir kez ayarlar, sadece imzayı "
            "değiştirirsiniz.\n\n"
            "Hedefin yanındaki 🟢/🔴 onu geçici olarak açıp kapatır, 🗑 siler."
        ),
        "uz": (
            "📤 <b>Bir nechta manzil, har biriga oʻz imzosi</b>\n"
            f"{RULE}\n\n"
            "Vazifa menyusida → «📤 Maqsad kanallar»\n\n"
            "Birinchi manzil ⭐️ asosiy hisoblanadi. Qolganlarini «➕ Manzil "
            "qoʻshish» bilan qoʻshing; har bir post hammasiga boradi.\n\n"
            "<b>✍️ Har kanalga alohida imzo</b>\n"
            "Har bir manzil yonida tugma bor:\n"
            "• ➕ oʻz imzosi yoʻq degani (vazifa sozlamalaridan foydalanadi)\n"
            "• ✍️ oʻz imzosi bor degani\n\n"
            "Uni bosib <b>faqat oʻsha kanal uchun</b> sozlaysiz:\n"
            "🔻 pastki matn  |  🔝 yuqori matn  |  🖋 almashtiruvchi imzo\n\n"
            "Shunday qilib bitta xabarni bir vaqtda uchta kanalingizga "
            "qoʻyasiz va har birining ostida oʻz manzili boʻladi.\n\n"
            "Qolgan hamma narsa (filtrlar, soʻz almashtirishlari, suv belgisi) "
            "vazifaning oʻzidan keladi — bir marta sozlaysiz va faqat imzoni "
            "oʻzgartirasiz.\n\n"
            "Manzil yonidagi 🟢/🔴 uni vaqtincha yoqadi yoki oʻchiradi, "
            "🗑 esa oʻchirib tashlaydi."
        ),
        "hi": (
            "📤 <b>कई गंतव्य, हर एक के अपने हस्ताक्षर</b>\n"
            f"{RULE}\n\n"
            "कार्य के मेन्यू में → «📤 गंतव्य चैनल»\n\n"
            "पहला गंतव्य ⭐️ मुख्य होता है। «➕ गंतव्य जोड़ें» से और जोड़ें; "
            "हर पोस्ट सभी में जाती है।\n\n"
            "<b>✍️ हर चैनल के अपने हस्ताक्षर</b>\n"
            "हर गंतव्य के पास एक बटन है:\n"
            "• ➕ यानी उसके अपने हस्ताक्षर नहीं (कार्य की सेटिंग इस्तेमाल होती है)\n"
            "• ✍️ यानी उसके अपने हैं\n\n"
            "उसे दबाकर <b>केवल उसी चैनल</b> के लिए तय करें:\n"
            "🔻 फ़ुटर  |  🔝 हेडर  |  🖋 वैकल्पिक हस्ताक्षर\n\n"
            "इस तरह एक ही खबर एक साथ अपने तीन चैनलों में डाल सकते हैं, और हर "
            "एक के नीचे उसका अपना नाम आएगा।\n\n"
            "बाकी सब (फ़िल्टर, शब्द बदलाव, वॉटरमार्क) कार्य से ही आता है — एक "
            "बार सेट करें और सिर्फ़ हस्ताक्षर बदलें।\n\n"
            "गंतव्य के पास 🟢/🔴 उसे अस्थायी रूप से चालू या बंद करता है, "
            "🗑 हटा देता है।"
        ),
        "id": (
            "📤 <b>Beberapa tujuan, masing-masing dengan tanda tangannya</b>\n"
            f"{RULE}\n\n"
            "Di menu tugas → «📤 Channel tujuan»\n\n"
            "Tujuan pertama adalah ⭐️ yang utama. Tambah lainnya dengan "
            "«➕ Tambah tujuan»; setiap postingan masuk ke semuanya.\n\n"
            "<b>✍️ Tanda tangan per channel</b>\n"
            "Di samping tiap tujuan ada tombol:\n"
            "• ➕ berarti tidak punya tanda tangan sendiri (memakai pengaturan tugas)\n"
            "• ✍️ berarti punya sendiri\n\n"
            "Mengetuknya membuat Anda bisa mengatur, <b>khusus channel itu</b>:\n"
            "🔻 footer  |  🔝 header  |  🖋 tanda tangan pengganti\n\n"
            "Jadi satu berita bisa masuk ke tiga channel Anda sekaligus, "
            "masing-masing ditandatangani dengan namanya sendiri.\n\n"
            "Selebihnya (filter, penggantian kata, watermark) datang dari "
            "tugasnya — diatur sekali dan Anda hanya mengganti tanda tangan.\n\n"
            "🟢/🔴 di samping tujuan menyalakan atau mematikannya sementara, "
            "🗑 menghapusnya."
        ),
        "pt": (
            "📤 <b>Vários destinos, cada um com sua assinatura</b>\n"
            f"{RULE}\n\n"
            "No menu da tarefa → «📤 Canais de destino»\n\n"
            "O primeiro destino é o ⭐️ principal. Adicione outros com "
            "«➕ Adicionar destino»; cada post vai para todos.\n\n"
            "<b>✍️ Assinatura por canal</b>\n"
            "Ao lado de cada destino há um botão:\n"
            "• ➕ significa que não tem assinatura própria (usa a da tarefa)\n"
            "• ✍️ significa que tem a sua\n\n"
            "Tocando nele você define, <b>só para aquele canal</b>:\n"
            "🔻 rodapé  |  🔝 cabeçalho  |  🖋 assinatura substituta\n\n"
            "Assim você coloca uma notícia em três canais seus de uma vez, "
            "cada um assinado com o próprio @.\n\n"
            "Todo o resto (filtros, substituições, marca d'água) vem da própria "
            "tarefa — configura uma vez e só troca a assinatura.\n\n"
            "🟢/🔴 ao lado de um destino liga ou desliga temporariamente, "
            "🗑 remove."
        ),
    },
}


def title(key: str, lang: str) -> str | None:
    """عنوان دکمه‌ی یک بخش به این زبان، یا None اگر ترجمه نشده."""
    return TITLES.get(key, {}).get(lang)


def body(key: str, lang: str) -> str | None:
    """متن یک بخش به این زبان، یا None اگر ترجمه نشده."""
    return BODIES.get(key, {}).get(lang)


def coverage(lang: str) -> int:
    """چند بخش به این زبان ترجمه شده — برای گزارش پیشرفت."""
    return sum(1 for entry in BODIES.values() if entry.get(lang))
